### ISSUE TITLE
Instructions for installation

### ISSUE THREAD

**Issue by anderlli0053** [stigmee/gdnative-cef#20]
Hello!

I'd be good if you write a simple installation steps as where specifically to include the files... i know that it should go into "modules" folder, but as of the file structure here i am not sure anymore as to what goes where..

@Lecrapouille

**Comment by Lecrapouille** [comment]
@anderlli0053 thanks you for your concern :) We are beginner in Godot and this module was thought as a part of a whole workspace (including Godot engine, godot cpp, other modules and the Godot application project) because it seems to us to be the simplest way of doing it. in where:
- https://github.com/stigmee/manifest knows the workspace
- https://github.com/stigmee/install knows how to compile the workspace (knows where Godot cpp is located, which modules to compile including this one)
- https://github.com/stigmee/stigmee is our Godot application which will get compiled libraries (modules, CEF).

So if I understand you well, you would like having a standalone build script like done in https://github.com/Lecrapouille/OffScreenCEF ? I will look at how to do it.

**Comment by Lecrapouille** [comment]
@anderlli0053 I added a python script to compile the example.

**Comment by anderlli0053** [comment]
@Lecrapouille  Thank You
